"""WireGuard keys, addresses and configuration files."""

import ipaddress
import re
import time

from byteguard import firewall
from byteguard.errors import ByteGuardError

NAME_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9_-]{0,31}")

# WireGuard renews a session about every two minutes while traffic flows.
ONLINE_WINDOW_SECONDS = 180

CONF_HEADER = (
    "# Generated by ByteGuard from its state file. Do not edit: the next\n"
    "# change made through ByteGuard overwrites this file.\n"
)


def keypair(run) -> tuple[str, str]:
    private = run(["wg", "genkey"]).stdout.strip()
    public = run(["wg", "pubkey"], input=private + "\n").stdout.strip()
    return private, public


def preshared_key(run) -> str:
    return run(["wg", "genpsk"]).stdout.strip()


def check_name(name: str) -> None:
    if not NAME_RE.fullmatch(name):
        raise ByteGuardError(
            "A device name uses letters, digits, '-' and '_', starts with a "
            "letter or digit, and is at most 32 characters long."
        )


def next_address(subnet: str, server_address: str, used) -> str:
    taken = {server_address, *used}
    for host in ipaddress.ip_network(subnet).hosts():
        if str(host) not in taken:
            return str(host)
    raise ByteGuardError(f"No free addresses are left in {subnet}.")


def server_config(state: dict) -> str:
    server = state["server"]
    prefix = ipaddress.ip_network(server["subnet"]).prefixlen
    up, down = firewall.hooks(
        state["firewall"]["mode"], server["iface"], server["port"], server["subnet"]
    )
    lines = [
        CONF_HEADER,
        "[Interface]",
        f"Address = {server['address']}/{prefix}",
        f"ListenPort = {server['port']}",
        f"PrivateKey = {server['private_key']}",
        f"MTU = {server['mtu']}",
        *(f"PostUp = {command}" for command in up),
        *(f"PostDown = {command}" for command in down),
    ]
    for device in state["devices"]:
        if not device["enabled"]:
            continue
        lines += [
            "",
            f"# {device['name']}",
            "[Peer]",
            f"PublicKey = {device['public_key']}",
            f"PresharedKey = {device['preshared_key']}",
            f"AllowedIPs = {device['address']}/32",
        ]
    return "\n".join(lines) + "\n"


def _endpoint(host: str, port: int) -> str:
    return f"[{host}]:{port}" if ":" in host else f"{host}:{port}"


def client_config(state: dict, device: dict) -> str:
    server = state["server"]
    lines = [
        "[Interface]",
        f"PrivateKey = {device['private_key']}",
        f"Address = {device['address']}/32",
        f"DNS = {', '.join(server['dns'])}",
        f"MTU = {server['mtu']}",
        "",
        "[Peer]",
        f"PublicKey = {server['public_key']}",
        f"PresharedKey = {device['preshared_key']}",
        f"Endpoint = {_endpoint(server['endpoint'], server['port'])}",
        # The VPN has no IPv6 of its own. Routing ::/0 into it stops IPv6
        # traffic from going around the VPN.
        "AllowedIPs = 0.0.0.0/0, ::/0",
        f"PersistentKeepalive = {server['keepalive']}",
    ]
    return "\n".join(lines) + "\n"


def parse_dump(text: str, now: float | None = None) -> dict[str, dict]:
    """Parse `wg show <interface> dump` into per-peer live figures, keyed by public key."""
    now = time.time() if now is None else now
    peers = {}
    # The first line describes the interface itself.
    for line in text.splitlines()[1:]:
        fields = line.split("\t")
        if len(fields) < 8:
            continue
        handshake = int(fields[4])
        peers[fields[0]] = {
            "endpoint": None if fields[2] == "(none)" else fields[2],
            "last_handshake": handshake or None,
            "online": bool(handshake) and now - handshake <= ONLINE_WINDOW_SECONDS,
            "received": int(fields[5]),
            "sent": int(fields[6]),
        }
    return peers
